# Plugin made by HegSiS
# For Otalia

choosing-menu:
  title: "&6Choix de la classe"
  pirate:
    item: SKULL_ITEM
    data: 0
    title: "&3Pirate"
    description:
      - " "
      - "&bClasse Pirate"
  titan:
    item: SKULL_ITEM
    data: 1
    title: "&6Titan"
    description:
      - " "
      - "&eClasse titan"

quest-type-menu:
  title: "&6&lCatégories de quêtes"
  categories:
    PVP:
      item: TNT
      data: 0
      title: "&cQuêtes PVP"
      description:
        - "&7Progression &f→ &e%progression%"
        - ""
        - "&7Quêtes terminée &f→ &a%done%"
        - "&7Quêtes restantes &f→ &c%available%"
    FARMEUR:
      item: WHEAT
      data: 0
      title: "&6Quêtes Farmeur"
      description:
        - "&7Progression &f→ &e%progression%"
        - ""
        - "&7Quêtes terminée &f→ &a%done%"
        - "&7Quêtes restantes &f→ &c%available%"
    PECHEUR:
      item: RAW_FISH
      data: 0
      title: "&3Quêtes Pêcheur"
      description:
        - "&7Progression &f→ &e%progression%"
        - ""
        - "&7Quêtes terminée &f→ &a%done%"
        - "&7Quêtes restantes &f→ &c%available%"
    CONSTRUCTEURMINEUR:
      item: GRASS
      data: 0
      title: "&2Quêtes Constructeur / Mineur"
      description:
        - "&7Progression &f→ &e%progression%"
        - ""
        - "&7Quêtes terminée &f→ &a%done%"
        - "&7Quêtes restantes &f→ &c%available%"
    DIVERS:
      item: GOLDEN_APPLE
      data: 0
      title: "&6Quêtes Diverses"
      description:
        - "&7Progression &f→ &e%progression%"
        - ""
        - "&7Quêtes terminée &f→ &a%done%"
        - "&7Quêtes restantes &f→ &c%available%"

necessary-xp:
  0to1: 10000
  1to2: 25000
  2to3: 40000
  3to4: 60000
  4to5: 90000
  5to6: 130000

rewards:
  pirate:
    level-1:
      - DIAMOND_SWORD;1;0
      - DIAMOND_PICKAXE
    level-2:
      - DIAMOND_SWORD;1;0
      - DIAMOND_PICKAXE
    level-3:
      - DIAMOND_SWORD;1;0
      - DIAMOND_PICKAXE
    level-4:
      - DIAMOND_SWORD;1;0
      - DIAMOND_PICKAXE
    level-5:
      - DIAMOND_SWORD;1;0
      - DIAMOND_PICKAXE
    level-6:
      - DIAMOND_SWORD;1;0
      - DIAMOND_PICKAXE
  titan:
    level-1:
      - DIAMOND_SWORD;1;0
      - DIAMOND_PICKAXE
    level-2:
      - DIAMOND_SWORD;1;0
      - DIAMOND_PICKAXE
    level-3:
      - DIAMOND_SWORD;1;0
      - DIAMOND_PICKAXE
    level-4:
      - DIAMOND_SWORD;1;0
      - DIAMOND_PICKAXE
    level-5:
      - DIAMOND_SWORD;1;0
      - DIAMOND_PICKAXE
    level-6:
      - DIAMOND_SWORD;1;0
      - DIAMOND_PICKAXE

messages:
  on-join-no-classe: "&2Vous n'avez toujours pas selectionné de classe &7: &a/classe &2!"
  join-classe: "&2Vous avez rejoint la classe &a%data% &2!"
