# Plugin made by HegSiS
# For Otalia

choosing-menu:
  title: "&6Choix de la classe"
  pirate:
    item: SKULL_ITEM
    data: 0
    title: "&3Pirate"
    description:
      - " "
      - "&bClasse Pirate"
  titan:
    item: SKULL_ITEM
    data: 1
    title: "&6Titan"
    description:
      - " "
      - "&eClasse titan"